#端口号
server:
    port: 80


spring:
    application:
        #服务别名——注册到zookeeper注册中心的名称
        name: cloud-consumer-order
    cloud:
        zookeeper:
            connect-string: 192.168.25.50:2181 #linux的ip加暴露的端口号
