server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址  lb://serviceName 是默认给我们实现的
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
          #                      - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]   #要求请求是 从此时间之后发来，否则失败
          #                      - Cookie=username,atguigu    #并且Cookie是username=zhangshuai才能访问
          #                      - Header=X-Request-Id, \d+     #请求头中要有X-Request-Id属性并且值为整数的正则表达式
          #                      - Method=GET
          #                      - Query=username, \d+         # 查询条件       其实还有 host域
          filters:
            - AddRequestParameter=X-Request-Id, 1024       # 过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id 值为1024


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
