server:
    port: 2002

spring:
    application:
        name: seata-storage-service
    cloud:
        alibaba:
            seata:
                enable: false
                # 自定义事务组名称需要与seata-server中的对应
                tx-service-group: my_test_tx_group #因为seata的file.conf文件中没有service模块，事务组名默认为my_test_tx_group
                #service要与tx-service-group对齐，vgroupMapping和grouplist在service的下一级，my_test_tx_group在再下一级
                service:
                    vgroupMapping:
                        #要和tx-service-group的值一致
                        my_test_tx_group: default
                    grouplist:
                        # seata seaver的 地址配置，此处可以集群配置是个数组
                        default: 192.168.25.50:8091
        nacos:
            discovery:
                server-addr: 192.168.25.50:8848  #nacos
    datasource:
        # 当前数据源操作类型
        type: com.alibaba.druid.pool.DruidDataSource
        # mysql驱动类
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.25.50:3306/seata_storage
        username: root
        password: '******'
feign:
    hystrix:
        enabled: false
logging:
    level:
        io:
            seata: info

mybatis:
    mapperLocations: classpath*:mapper/*.xml
