server:
    port: 84


spring:
    application:
        name: nacos-order-consumer
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.25.50:8848
        sentinel:
            transport:
                dashboard: 192.168.25.50:8858
                port: 8719

service-url:
    nacos-user-service: http://nacos-payment-provider

#对Feign的支持
feign:
    sentinel:
        enabled: true