#微服务建议一定要写服务端口号和微服务名称
server:
    #端口号
    port: 80

spring:
    application:
        #微服务名称
        name: cloud-order-service
    #数据库配置
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #mysql5.x的没有cj
        driver-class-name: com.mysql.jdbc.Driver
        #记得先创建数据库
        url: jdbc:mysql://localhost:3306/cloud2020
        username: root
        password: 123456

#mybatis配置
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.atguigu.springcloud.entities  #所有Entity别名类所在包

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    
    instance:
        instance-id: order80
        prefer-ip-address: true   #访问路径可以显示ip地址
    # 修改名字 实际山在 eureka中就变了 ，